### ISSUE TITLE
无法查询2017-2018发生的变更

### ISSUE THREAD

**Issue by heyang95** [lizy14/division-changes#2]
原标题：程序好像有一点点问题，如果是 translate("620824",2017)，似乎并没有办法得到最新的区县名称。

**Comment by lizy14** [comment]
设计如此，`translate` 返回的是行政区划代码。你的例子`translate("620824",2017)`返回`['620824']`，这是因为2017年以来甘肃省-平凉市-华亭县没有发生过拆分合并等变更

**Comment by lizy14** [comment]
你的需求可以使用另一个函数`code_to_readable`，详见`translate.py`的代码
```python
>>> from translate import code_to_readable
>>> code_to_readable("620824",2017)
'甘肃省-平凉市-华亭县[县级](620824)'
```

**Comment by heyang95** [comment]
您好，感谢您的回信。首先，感谢您设计了这个程序。其次，关于我的问题，可能是因为我没说清楚。2017年华亭县的行政编码为620824，但是在2018年时，华亭县更名为华亭市，行政编码变更为620881，且这个编码的变化体现在了您整理的表rulels_generated/code-changes.csv中（倒数第一行），只不过执行命令translate("620824",2017)无法返回得到620881，仍然是620824。除此之外，我发现针对2017-2018年变更的区县情况，似乎都无法得到最新的区县代码。我水平有限，不知道应该怎么修改程序。可能还要麻烦您有时间的时候再看下代码。最后，请允许我再次表示感谢。因为您的这个程序，我减少了好多工作量啊，谢谢。
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 祝好 何洋




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhaoyang"<notifications@github.com&gt;; 
发送时间: 2020年12月2日(星期三) 下午5:40
收件人: "lizy14/division-changes"<division-changes@noreply.github.com&gt;; 
抄送: "何洋"<393829124@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lizy14/division-changes] 程序好像有一点点问题，如果是 translate(&quot;620824&quot;,2017)，似乎并没有办法得到最新的区县名称。 (#2)





 
设计如此，translate 返回的是行政区划代码。你的例子translate("620824",2017)返回['620824']，这是因为2017年以来兰州市西固区没有发生过拆分合并等变更

**Comment by lizy14** [comment]
感谢您的反馈。我已修改代码，目前已经可以查到2017-2018年发生的变更。

**Comment by heyang95** [comment]
谢谢您~&nbsp; 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 祝好~






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhaoyang"<notifications@github.com&gt;; 
发送时间: 2020年12月2日(星期三) 晚上6:47
收件人: "lizy14/division-changes"<division-changes@noreply.github.com&gt;; 
抄送: "何洋"<393829124@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [lizy14/division-changes] 程序好像有一点点问题，如果是 translate(&quot;620824&quot;,2017)，似乎并没有办法得到最新的区县名称。 (#2)





 
感谢您的反馈。我已修改代码，目前已经可以查到2017-2018年发生的变更。
